名字: "打卡"

# 明确触发条件
在:
工作流_调度:  # 手动触发
日程安排:
    - 时间单位: "55 23 * * *"-克朗:“59 23 * * *”
    - 时间单位: "0 0 * * *"-克朗:“26 0 * * *”
    - 时间单位: "40 9 * * *"- cron: "50 9 * * *" # UTC 09:00 /北京时间 17:00# UTC 09:00 / 北京时间 17:00

# 配置并发控制，避免任务重叠执行
并发:
组: 群组:$ { { github . workflow } }-$ { { github . ref } }{{ github.workflow }}-${{ github.ref }}
正在取消: 真实的

工作:
建设:
连续运行: 运行:Ubuntu-最新版
超时-分钟: 超时-分钟:10 #添加超时限制# 添加超时限制

步伐:
# 设置时区为亚洲/上海# 设置时区为亚洲/上海
      - 名字: - name:设置时区
使用: 用法:szenius/set-timezone@v2.0
随着:
时区Linux: “亚洲/上海”

      # 检出代码仓库
      - 名字: 签出存储库
使用: 动作/签出@v4
        with:
          fetch-depth: 1  # 优化克隆深度

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'  # 启用 pip 缓存
          check-latest: true  # 检查是否有更新的补丁版本

      # 缓存 pip 依赖
      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 执行任务
      - name: Run sign in script
        env:
          USER: ${{ secrets.USER }}
          TZ: Asia/Shanghai  # 确保脚本运行时也使用正确的时区
        run: |
          python main.py
